### ISSUE TITLE
Information on How You got the exact Bytes

### ISSUE THREAD

**Issue by artinmare** [juamiso/ANT_BMS#4]
Hi, Sorry to asking You this way, hope You don't mind because I don't know how to contact You.
First of all, Thank You for sharing the project You've done, it's really helping me to do my own project

Back to the point :

I really want to know how you able to know the exact bytes that represent certain information. As example on line 49 of bms_post.py, You use "data = (Antw33.encode('hex') [(111*2):(114*2+2)])" to get the power data. The same as when You get the Voltage of each battery cell. Can You please explain to me how You know that the information You're looking for is on those bytes i.e [(111*2):(114*2+2)]. Is it done by Trial and Error or is there a way to know the exact location for the bytes ? If so, would You mind to share some links for the resources You've used to learn the craft.

I hope You get what I am trying to say, English is not my main language.
Thank You very much.
Sincerly, Artin

**Comment by juamiso** [comment]
Hi. I used a word document that was in a zip file which I downloaded from “ant” server. I am now in holyday and do not have access to the links.
So, no, it was not trial and error

**Comment by juamiso** [comment]
I found it 👨‍💻 
Here the link:
https://drive.google.com/open?id=1YAztDlG9y2ftR_nmfDPqdegoxXojhzlP
Which I found here:
http://rjxzstech.com/new/ant-bms-instructions.html

**Comment by artinmare** [comment]
Oh, Thank You very much for your effort.
It really helped me out 😁

Have a nice holiday 😄
