### ISSUE TITLE
windows keep disconnecting + temp reading?

### ISSUE THREAD

**Issue by wesellcells** [juamiso/ANT_BMS#7]
Good morning, i've managed to get script working on win and comport.
sometimes it gives me error because cant connect to com port (work for hours then suddently stops)

any tips on what to do?

then, BMS should have 2 sensors, but i can t understand if i can read from hex extracted or we need another command.

last :  how i can manage more than 1 bms? i'm trying to change bt address, but seller can't help much, app VBMS instead of change the address send a "switch to lifepo"...

**Comment by juamiso** [comment]
Sorry not experience on win. My setup is stable but I know a guy who is having often connection drops (bluetooth probably not stable in his environment). 
Also I have no experience with multiple bms setups

**Comment by wesellcells** [comment]
thanks for reply. i managed to keep it connected shorting the red/black cable.
now is stable.  i managed to get temp reading from sensor
(Antw33.hex() [(91 * 2):(92 * 2+2)])
(Antw33.hex() [(93  * 2):(94 * 2+2)])
(Antw33.hex() [(95 * 2):(96 * 2 +2)])

now i miss the change addres... seems i've got an app without the change address features

**Comment by juamiso** [comment]
Thanks for sharing. I still have to wire the temperatur sensors for the cells ... however I am using now the LCD Display too, and AFAIK the same connector is used for the temperatures? So maybe I can not wire this up.

Have you tried with the apple iOS app as well?

**Comment by wesellcells** [comment]
not with iOS, but i've managed to understand that problem was crappy app sent from seller. i've found the new/true app and now i have 2 running with 2 different address

now i'm trying to connect with win and their com port to datalog 8 battery bank 24v 80ah


edit: now i have 2 bms running together. in windows i'm using multiple com port, and using serial. now need to understand how to dont use serial with multiple address together

**Comment by juamiso** [comment]
New branch has included the battery temp monitoring.
